### ISSUE TITLE
chatview2 is incompatible with flutter_facebook_auth >=6.0.0

### ISSUE THREAD

**Issue by khoafornia** [Pranavmaid/chatview2#2]
Because every version of chatview2 depends on http ^0.13.5 and facebook_auth_desktop >=1.0.0 depends on http ^1.0.0, chatview2 is incompatible with facebook_auth_desktop >=1.0.0.
And because flutter_facebook_auth >=6.0.0 depends on facebook_auth_desktop ^1.0.0, chatview2 is incompatible with flutter_facebook_auth >=6.0.0.
So, because PROJECT depends on both chatview2 ^0.0.4 and flutter_facebook_auth ^6.0.0, version solving failed.

**Comment by Pranavmaid** [comment]
Hi @khoafornia pkg is updated use the 0.0.9 version
