### ISSUE TITLE
The image inside Readme.md hangs up

### ISSUE THREAD

**Issue by sunjianan9900** [Pranavmaid/chatview2#3]
this:

https://raw.githubusercontent.com/SimformSolutionsPvtLtd/flutter_chat_ui/main/preview/chatview2.gif

**Comment by Pranavmaid** [comment]
thank you for the info

**Comment by sunjianan9900** [comment]
Currently showing perfectly at pubdev.top
![image](https://github.com/Pranavmaid/chatview2/assets/10936316/7eee5cf9-ec66-4c8c-a50c-8408153856a3)
